[package]
name = "jordanbray-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = "3.2.0"
rand = { version = "0.8.5", features = ["small_rng"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = 0
